### ISSUE TITLE
Links Not Auto-Opening

### ISSUE THREAD

**Issue by Wild1145** [ScreenShottr/ScreenShottr-Windows#2]
This is a issue with Windows 8 running Firefox.

The links are no longer automatically opening for me with the images. While its not a big deal as I normally close them anyway, its hard then to know if the screen shot was uploaded, or if it failed, or if it was still uploading.

**Comment by Fyrsta** [comment]
This is probably an issue with Firefox not supporting the way uploaded images are opened. Has it ever worked before on Firefox? Also, has it worked on Windows 8 with other browsers?

**Comment by Wild1145** [comment]
It works fine on other browsers, and I dont remember ever having any issues with firefox before the last couple of days.

**Comment by TheCJGCJG** [comment]
Application has been abandoned, rewrites are in progress.
